#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
DIST = ROOT / "dist"
INTENT = ROOT / "goal" / "renderer_intent.json"

def load_intent():
    return json.loads(INTENT.read_text(encoding="utf-8"))

def project(intent, x, y, z):
    p = intent["projection"]
    return (
        p["origin_x"] + x*p["x_axis"]["dx"] + y*p["y_axis"]["dx"] + z*p["z_axis"]["dx"],
        p["origin_y"] + x*p["x_axis"]["dy"] + y*p["y_axis"]["dy"] + z*p["z_axis"]["dy"],
    )

def asm_header():
    return "; GENERATED BY WORKBENCH\n; Source: goal/renderer_intent.json\n; Generator: tools/generate_blockout_renderer.py\n; Do not edit by hand.\n\n"

def main():
    intent = load_intent()
    pit = intent["pit"]
    SRC.mkdir(parents=True, exist_ok=True)
    DIST.mkdir(parents=True, exist_ok=True)

    entries = []
    for z in range(pit["height"]):
        for y in range(pit["depth"]):
            for x in range(pit["width"]):
                sx, sy = project(intent, x, y, z)
                entries.append({"x": x, "y": y, "z": z, "screen_x": sx, "screen_y": sy})

    segments = []
    model_segments = []
    w, d, h = pit["width"], pit["depth"], pit["height"]

    for x in range(w + 1):
        model_segments.append(((x, 0, 0), (x, d, 0)))
    for y in range(d + 1):
        model_segments.append(((0, y, 0), (w, y, 0)))
    for corner in [(0,0,0), (w,0,0), (0,d,0), (w,d,0)]:
        x, y, z = corner
        model_segments.append(((x, y, z), (x, y, h)))
    for z in range(3, h + 1, 3):
        model_segments += [((0,0,z),(w,0,z)), ((w,0,z),(w,d,z)), ((w,d,z),(0,d,z)), ((0,d,z),(0,0,z))]

    for a, b in model_segments:
        x1, y1 = project(intent, *a)
        x2, y2 = project(intent, *b)
        segments.append({"start": list(a), "end": list(b), "x1": x1, "y1": y1, "x2": x2, "y2": y2})

    projection_asm = [asm_header(), "projection_table:", "    ; cell index = z * width * depth + y * width + x", "    ; each entry: screen_x, screen_y"]
    for e in entries:
        projection_asm.append(f"    .byte {e['screen_x']}, {e['screen_y']}   ; x={e['x']} y={e['y']} z={e['z']}")
    (SRC / "generated_projection_table.s").write_text("\n".join(projection_asm) + "\n", encoding="utf-8")

    pit_asm = [asm_header(), "pit_line_segment_count:", f"    .byte {len(segments)}", "", "pit_line_segments:", "    ; x1, y1, x2, y2"]
    for s in segments:
        pit_asm.append(f"    .byte {s['x1']}, {s['y1']}, {s['x2']}, {s['y2']}   ; {s['start']} -> {s['end']}")
    (SRC / "generated_pit_line_segments.s").write_text("\n".join(pit_asm) + "\n", encoding="utf-8")

    renderer = asm_header() + """draw_pit_wireframe:
    ; Milestone 3: iterate pit_line_segments and call draw_projected_edge.
    rts

draw_projected_cube:
    ; Milestone 4: draw one projected cube from projection_table.
    rts

draw_active_piece:
    ; Milestone 5: draw active piece cubes.
    rts

draw_projected_edge:
    ; Milestone 3: draw one projected edge.
    rts
"""
    (SRC / "generated_renderer.s").write_text(renderer, encoding="utf-8")

    (DIST / "projection_table.json").write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
    (DIST / "pit_line_segments.json").write_text(json.dumps(segments, indent=2) + "\n", encoding="utf-8")

    print(f"Generated {len(entries)} projection entries.")
    print(f"Generated {len(segments)} pit line segments.")

if __name__ == "__main__":
    main()
