#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
SRC = ROOT / "src"

COLOR_IDS = {
    "red_light": 2,
    "red_mid": 3,
    "red_mid_dark": 4,
    "red_dark": 5,
    "red_deep": 6,
}

def ensure_cube_faces() -> None:
    if not (DIST / "single_cube_polygon_faces.json").exists():
        subprocess.run(["python3", "tools/render_single_cube_polygon_svg.py"], cwd=ROOT, check=True)

def polygon_spans(points: list[dict]) -> list[dict]:
    """
    Convert one convex quad into integer horizontal spans.

    Uses edge intersections per scanline. This is intentionally generated on
    the Workbench side so C64 code can consume spans rather than solve polygon math.
    """
    xy = [(int(p["x"]), int(p["y"])) for p in points]
    min_y = max(0, min(y for x, y in xy))
    max_y = min(199, max(y for x, y in xy))

    spans: list[dict] = []

    for y in range(min_y, max_y + 1):
        intersections: list[float] = []
        for i in range(len(xy)):
            x1, y1 = xy[i]
            x2, y2 = xy[(i + 1) % len(xy)]

            if y1 == y2:
                continue

            low_y = min(y1, y2)
            high_y = max(y1, y2)

            # Half-open edge rule avoids double-counting vertices.
            if low_y <= y < high_y:
                t = (y - y1) / (y2 - y1)
                intersections.append(x1 + t * (x2 - x1))

        if len(intersections) < 2:
            continue

        intersections.sort()
        x_start = max(0, round(intersections[0]))
        x_end = min(255, round(intersections[-1]))

        if x_start <= x_end:
            spans.append({"y": y, "x_start": x_start, "x_end": x_end})

    return spans

def main() -> None:
    ensure_cube_faces()

    faces_path = DIST / "single_cube_polygon_faces.json"
    data = json.loads(faces_path.read_text(encoding="utf-8"))

    face_spans = []
    for face_index, face in enumerate(data["faces"]):
        shade = face["shade"]
        spans = polygon_spans(face["points"])
        face_spans.append({
            "face_index": face_index,
            "face_name": face["name"],
            "shade": shade,
            "color_id": COLOR_IDS.get(shade, 1),
            "span_count": len(spans),
            "spans": spans,
        })

    total_spans = sum(face["span_count"] for face in face_spans)

    out_json = DIST / "single_cube_polygon_spans.json"
    out_json.write_text(json.dumps({
        "source": "dist/single_cube_polygon_faces.json",
        "purpose": "C64-facing generated horizontal spans for one red shaded cube",
        "format": "face_index, color_id, y, x_start, x_end",
        "total_spans": total_spans,
        "faces": face_spans,
    }, indent=2) + "\n", encoding="utf-8")

    lines = [
        "; GENERATED BY WORKBENCH",
        "; Source: dist/single_cube_polygon_faces.json",
        "; Generator: tools/generate_single_cube_polygon_spans.py",
        "; Purpose: C64-facing horizontal span fill data for one shaded cube.",
        "; Do not edit by hand.",
        "",
        "single_cube_span_face_count:",
        f"    .byte {len(face_spans)}",
        "",
        "single_cube_span_total_count:",
        f"    .word {total_spans}",
        "",
        "single_cube_spans:",
        "    ; face_index, color_id, y, x_start, x_end",
    ]

    for face in face_spans:
        lines.append(f"    ; {face['face_name']} shade={face['shade']} spans={face['span_count']}")
        for span in face["spans"]:
            lines.append(
                f"    .byte {face['face_index']}, {face['color_id']}, {span['y']}, {span['x_start']}, {span['x_end']}"
            )

    lines.extend([
        "",
        "single_cube_spans_end:",
        "",
    ])

    out_asm = SRC / "generated_single_cube_spans.s"
    out_asm.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {out_json}")
    print(f"Wrote {out_asm}")
    print(f"Generated {total_spans} horizontal spans from {len(face_spans)} cube faces.")

if __name__ == "__main__":
    main()
