#!/usr/bin/env python3
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
SRC = ROOT / "src"

def ensure_source():
    subprocess.run(["python3", "tools/generate_moving_cube_same_depth_spans.py"], cwd=ROOT, check=True)

def bitmap_offset(byte_x, y):
    return (y // 8) * 320 + byte_x * 8 + (y % 8)

def mask_for(x0, x1, byte_x):
    left = byte_x * 8
    mask = 0
    for x in range(max(x0, left), min(x1, left + 7) + 1):
        mask |= 1 << (7 - (x % 8))
    return mask

def main():
    ensure_source()
    src = json.loads((DIST / "moving_cube_same_depth_frames.json").read_text())

    frames = []
    estimates = []
    total_records = 0

    for frame in src["frames"]:
        records = []
        for face in frame["span_faces"]:
            for span in face["spans"]:
                for byte_x in range(span["x_start"] // 8, span["x_end"] // 8 + 1):
                    mask = mask_for(span["x_start"], span["x_end"], byte_x)
                    if mask:
                        records.append({
                            "frame_index": frame["frame_index"],
                            "face_index": face["face_index"],
                            "color_id": face["color_id"],
                            "y": span["y"],
                            "byte_x": byte_x,
                            "bitmap_offset": bitmap_offset(byte_x, span["y"]),
                            "mask": mask,
                        })

        full = sum(1 for r in records if r["mask"] == 255)
        masked = len(records) - full
        # Planning estimate: byte write oriented, not cycle-perfect.
        cycles = full * 14 + masked * 28 + len(records) * 8
        total_records += len(records)
        frames.append({
            "frame_index": frame["frame_index"],
            "cube": frame["cube"],
            "source_total_spans": frame["total_spans"],
            "source_total_pixels": frame["total_pixels"],
            "byte_record_count": len(records),
            "full_byte_writes": full,
            "masked_byte_writes": masked,
            "records": records,
        })
        estimates.append({
            "frame_index": frame["frame_index"],
            "byte_record_count": len(records),
            "estimated_cycles": cycles,
            "within_60hz_budget": cycles < 16667,
            "within_50hz_budget": cycles < 20000,
        })

    max_cycles = max(e["estimated_cycles"] for e in estimates)
    out = {
        "source": "dist/moving_cube_same_depth_frames.json",
        "purpose": "optimized byte/mask span payload for same-depth moving cube",
        "frame_count": len(frames),
        "total_byte_records": total_records,
        "max_byte_records_per_frame": max(f["byte_record_count"] for f in frames),
        "optimized_c64_realtime_estimate": {
            "assumption": "precomputed bitmap byte offsets and masks; C64 writes bytes instead of looping pixels",
            "max_estimated_frame_cycles": max_cycles,
            "approx_1mhz_60hz_budget": 16667,
            "approx_1mhz_50hz_budget": 20000,
            "within_60hz_budget": max_cycles < 16667,
            "within_50hz_budget": max_cycles < 20000,
            "note": "Planning estimate only. Next proof should time the loop in C64/VICE."
        },
        "frame_estimates": estimates,
        "frames": frames,
    }

    DIST.mkdir(parents=True, exist_ok=True)
    SRC.mkdir(parents=True, exist_ok=True)
    (DIST / "moving_cube_same_depth_byte_spans.json").write_text(json.dumps(out, indent=2) + "\n")

    lines = [
        "; GENERATED BY WORKBENCH",
        "; Source: dist/moving_cube_same_depth_byte_spans.json",
        "; Record: frame, face, color, y, byte_x, offset_lo, offset_hi, mask",
        "",
        "moving_cube_byte_frame_count:",
        f"    .byte {len(frames)}",
        "",
        "moving_cube_byte_span_records:",
    ]
    for frame in frames:
        lines.append(f"    ; frame {frame['frame_index']} records {frame['byte_record_count']}")
        for r in frame["records"]:
            off = r["bitmap_offset"]
            lines.append(f"    .byte {r['frame_index']}, {r['face_index']}, {r['color_id']}, {r['y']}, {r['byte_x']}, {off & 255}, {(off >> 8) & 255}, {r['mask']}")
    lines += ["", "moving_cube_byte_span_total_count:", f"    .word {total_records}", ""]
    (SRC / "generated_moving_cube_byte_spans.s").write_text("\n".join(lines))

    print("Wrote dist/moving_cube_same_depth_byte_spans.json")
    print("Wrote src/generated_moving_cube_byte_spans.s")
    print(f"Max estimated byte-span cycles/frame: {max_cycles}")

if __name__ == "__main__":
    main()
