#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
DIST = ROOT / "dist"
INTENT = ROOT / "goal" / "renderer_intent.json"

def load_intent() -> dict:
    return json.loads(INTENT.read_text(encoding="utf-8"))

def lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t

def ring_for_z(intent: dict, z: int) -> dict:
    """
    Return an explicit perspective ring for z.

    If z lies between declared rings, interpolate. This keeps the model precise
    while allowing the intent to name the visual guide rings directly.
    """
    rings = sorted(intent["projection"]["depth_rings"], key=lambda r: r["z"])
    if z <= rings[0]["z"]:
        return dict(rings[0])
    if z >= rings[-1]["z"]:
        return dict(rings[-1])

    for a, b in zip(rings, rings[1:]):
        if a["z"] <= z <= b["z"]:
            span = b["z"] - a["z"]
            t = 0 if span == 0 else (z - a["z"]) / span
            return {
                "z": z,
                "width": round(lerp(a["width"], b["width"], t)),
                "height": round(lerp(a["height"], b["height"], t)),
            }

    raise ValueError(f"No perspective ring for z={z}")

def perspective_project(intent: dict, x: int, y: int, z: int) -> tuple[int, int]:
    """
    Top-down perspective pit projection.

    x/y define the visible board opening.
    z is depth into the well.
    Deeper z levels use smaller explicit/inferred rings converging toward center.
    """
    pit = intent["pit"]
    p = intent["projection"]
    ring = ring_for_z(intent, z)

    cx = p["center_x"]
    cy = p["center_y"]
    width = ring["width"]
    height = ring["height"]

    left = cx - width / 2
    top = cy - height / 2

    sx = round(left + (x * width / pit["width"]))
    sy = round(top + (y * height / pit["depth"]))
    return sx, sy

def project(intent: dict, x: int, y: int, z: int) -> tuple[int, int]:
    projection_type = intent["projection"]["type"]
    if projection_type == "top_down_perspective_rings":
        return perspective_project(intent, x, y, z)
    raise ValueError(f"Unsupported projection type for Lab 011: {projection_type}")

def projection_entries(intent: dict) -> list[dict]:
    pit = intent["pit"]
    entries = []
    for z in range(pit["height"]):
        for y in range(pit["depth"]):
            for x in range(pit["width"]):
                sx, sy = project(intent, x, y, z)
                entries.append({
                    "x": x,
                    "y": y,
                    "z": z,
                    "screen_x": sx,
                    "screen_y": sy,
                })
    return entries

def pit_line_segments(intent: dict) -> list[dict]:
    pit = intent["pit"]
    width = pit["width"]
    depth = pit["depth"]
    height = pit["height"]
    guide_interval = intent["renderer"].get("depth_guide_interval", 3)

    model_segments = []

    # Top board opening: full 5x5 visible grid.
    for x in range(width + 1):
        model_segments.append(((x, 0, 0), (x, depth, 0)))
    for y in range(depth + 1):
        model_segments.append(((0, y, 0), (width, y, 0)))

    # Explicit visual guide rings at readable z intervals.
    for z in range(guide_interval, height + 1, guide_interval):
        model_segments.append(((0, 0, z), (width, 0, z)))
        model_segments.append(((width, 0, z), (width, depth, z)))
        model_segments.append(((width, depth, z), (0, depth, z)))
        model_segments.append(((0, depth, z), (0, 0, z)))

    # Perspective rails from top perimeter to deepest ring.
    for x in range(width + 1):
        model_segments.append(((x, 0, 0), (x, 0, height)))
        model_segments.append(((x, depth, 0), (x, depth, height)))
    for y in range(1, depth):
        model_segments.append(((0, y, 0), (0, y, height)))
        model_segments.append(((width, y, 0), (width, y, height)))

    segments = []
    for start, end in model_segments:
        x1, y1 = project(intent, *start)
        x2, y2 = project(intent, *end)
        segments.append({
            "start": list(start),
            "end": list(end),
            "x1": x1,
            "y1": y1,
            "x2": x2,
            "y2": y2,
        })
    return segments

def asm_header(source: str) -> str:
    return (
        "; GENERATED BY WORKBENCH\n"
        f"; Source: {source}\n"
        "; Generator: tools/generate_blockout_renderer.py\n"
        "; Projection: top_down_perspective_rings\n"
        "; Do not edit by hand.\n\n"
    )

def write_projection_asm(entries: list[dict]) -> None:
    lines = [asm_header("goal/renderer_intent.json")]
    lines.append("projection_table:")
    lines.append("    ; cell index = z * width * depth + y * width + x")
    lines.append("    ; each entry: screen_x, screen_y")
    for entry in entries:
        lines.append(
            f"    .byte {entry['screen_x']}, {entry['screen_y']}   ; x={entry['x']} y={entry['y']} z={entry['z']}"
        )
    lines.append("")
    (SRC / "generated_projection_table.s").write_text("\n".join(lines), encoding="utf-8")

def write_pit_segments_asm(segments: list[dict]) -> None:
    lines = [asm_header("goal/renderer_intent.json")]
    lines.append("pit_line_segment_count:")
    lines.append(f"    .byte {len(segments)}")
    lines.append("")
    lines.append("pit_line_segments:")
    lines.append("    ; x1, y1, x2, y2")
    for segment in segments:
        lines.append(
            f"    .byte {segment['x1']}, {segment['y1']}, {segment['x2']}, {segment['y2']}   ; {segment['start']} -> {segment['end']}"
        )
    lines.append("")
    (SRC / "generated_pit_line_segments.s").write_text("\n".join(lines), encoding="utf-8")

def write_perspective_rings_asm(intent: dict) -> None:
    rings = sorted(intent["projection"]["depth_rings"], key=lambda r: r["z"])
    lines = [asm_header("goal/renderer_intent.json")]
    lines.append("perspective_ring_count:")
    lines.append(f"    .byte {len(rings)}")
    lines.append("")
    lines.append("perspective_rings:")
    lines.append("    ; z, width, height")
    for ring in rings:
        lines.append(f"    .byte {ring['z']}, {ring['width']}, {ring['height']}")
    lines.append("")
    (SRC / "generated_perspective_rings.s").write_text("\n".join(lines), encoding="utf-8")

def write_renderer_stub_asm() -> None:
    text = asm_header("goal/renderer_intent.json") + """draw_pit_wireframe:
    ; Contract:
    ;   Iterate pit_line_segments and call draw_line or draw_projected_edge.
    rts


draw_projected_cube:
    ; Contract:
    ;   Input A = cube cell index.
    ;   Uses projection_table.
    rts


draw_active_piece:
    ; Contract:
    ;   Uses active_piece_start and active_piece_cubes.
    ;   Calls draw_projected_cube for each cube.
    rts


draw_projected_edge:
    ; Contract:
    ;   Draw one generated edge.
    rts
"""
    (SRC / "generated_renderer.s").write_text(text, encoding="utf-8")

def write_projection_metadata(intent: dict, projections: list[dict], segments: list[dict]) -> None:
    metadata = {
        "projection_type": intent["projection"]["type"],
        "view": intent["renderer"].get("view"),
        "depth_guide_interval": intent["renderer"].get("depth_guide_interval"),
        "depth_rings": intent["projection"]["depth_rings"],
        "projection_entries": len(projections),
        "pit_line_segments": len(segments),
    }
    (DIST / "projection_metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

def main() -> None:
    SRC.mkdir(parents=True, exist_ok=True)
    DIST.mkdir(parents=True, exist_ok=True)

    intent = load_intent()
    projections = projection_entries(intent)
    segments = pit_line_segments(intent)

    write_projection_asm(projections)
    write_pit_segments_asm(segments)
    write_perspective_rings_asm(intent)
    write_renderer_stub_asm()
    write_projection_metadata(intent, projections, segments)

    (DIST / "projection_table.json").write_text(json.dumps(projections, indent=2) + "\n", encoding="utf-8")
    (DIST / "pit_line_segments.json").write_text(json.dumps(segments, indent=2) + "\n", encoding="utf-8")

    print(f"Generated {len(projections)} projection entries.")
    print(f"Generated {len(segments)} pit line segments.")
    print("Generated explicit top-down perspective ring projection.")

if __name__ == "__main__":
    main()
