#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
combined = ""
for rel in [
    "src/generated_projection_table.s",
    "src/generated_pit_line_segments.s",
    "src/generated_renderer.s",
]:
    path = ROOT / rel
    if not path.exists():
        raise SystemExit(f"Missing generated ASM: {rel}")
    text = path.read_text(encoding="utf-8")
    if "GENERATED BY WORKBENCH" not in text:
        raise SystemExit(f"Missing generated marker: {rel}")
    combined += "\n" + text

for label in [
    "projection_table:",
    "pit_line_segments:",
    "draw_pit_wireframe:",
    "draw_projected_cube:",
    "draw_active_piece:",
    "draw_projected_edge:",
]:
    if label not in combined:
        raise SystemExit(f"Missing label: {label}")

print("OK: generated renderer ASM contract verified.")
