#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
json_path = ROOT / "dist" / "moving_cube_same_depth_frames.json"
asm_path = ROOT / "src" / "generated_moving_cube_spans.s"
svg_path = ROOT / "captures" / "blockout_moving_cube_same_depth_preview.svg"

for path in [json_path, asm_path, svg_path]:
    if not path.exists():
        raise SystemExit(f"Missing moving cube artifact: {path.relative_to(ROOT)}")

data = json.loads(json_path.read_text(encoding="utf-8"))

if data.get("movement") != "x changes, y/z/depth/height held constant":
    raise SystemExit("Moving cube proof does not hold depth positioning constant")

frames = data.get("frames", [])
if len(frames) < 4:
    raise SystemExit(f"Expected at least 4 movement frames, found {len(frames)}")

z_values = {frame["cube"]["z"] for frame in frames}
y_values = {frame["cube"]["y"] for frame in frames}
height_values = {frame["cube"]["height"] for frame in frames}
if len(z_values) != 1 or len(y_values) != 1 or len(height_values) != 1:
    raise SystemExit("Cube depth positioning is not held constant across frames")

x_values = [frame["cube"]["x"] for frame in frames]
if x_values != sorted(x_values) or len(set(x_values)) != len(x_values):
    raise SystemExit(f"Cube x movement is not a clean lateral sweep: {x_values}")

for frame in frames:
    if frame.get("total_spans", 0) <= 0:
        raise SystemExit(f"Frame has no spans: {frame['frame_index']}")
    if frame.get("total_pixels", 0) <= 0:
        raise SystemExit(f"Frame has no pixels: {frame['frame_index']}")
    if len(frame.get("faces", [])) != 5:
        raise SystemExit(f"Frame does not have 5 cube faces: {frame['frame_index']}")

estimate = data.get("c64_realtime_estimate", {})
if "estimated_frame_cycles" not in estimate:
    raise SystemExit("Missing realtime cycle estimate")
if estimate["estimated_frame_cycles"] <= 0:
    raise SystemExit("Invalid realtime cycle estimate")
if not estimate.get("within_50hz_budget"):
    print(f"WATCH: conservative naive pixel estimate exceeds 50Hz budget: {estimate}")

asm = asm_path.read_text(encoding="utf-8")
for marker in [
    "GENERATED BY WORKBENCH",
    "moving_cube_frame_count:",
    "moving_cube_span_records:",
    "moving_cube_span_total_count:",
]:
    if marker not in asm:
        raise SystemExit(f"Moving cube ASM missing marker: {marker}")

svg = svg_path.read_text(encoding="utf-8")
for marker in [
    "frame 0",
    "frame 1",
    "frame 2",
    "frame 3",
    "same-depth",
    "red_light",
]:
    if marker not in svg:
        raise SystemExit(f"Moving cube SVG missing marker: {marker}")

print("OK: same-depth moving cube span payload verified.")
