#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spans_path = ROOT / "dist" / "single_cube_polygon_spans.json"
asm_path = ROOT / "src" / "generated_single_cube_spans.s"

if not spans_path.exists():
    raise SystemExit("Missing dist/single_cube_polygon_spans.json")
if not asm_path.exists():
    raise SystemExit("Missing src/generated_single_cube_spans.s")

data = json.loads(spans_path.read_text(encoding="utf-8"))
if data.get("source") != "dist/single_cube_polygon_faces.json":
    raise SystemExit("Span data source is not the generated cube face quads")

faces = data.get("faces", [])
if len(faces) != 5:
    raise SystemExit(f"Expected spans for 5 cube faces, found {len(faces)}")

total = data.get("total_spans", 0)
if total < 5:
    raise SystemExit(f"Too few spans generated: {total}")

required_names = {"top_face", "north_wall", "east_wall", "south_wall", "west_wall"}
names = {face.get("face_name") for face in faces}
if names != required_names:
    raise SystemExit(f"Unexpected span face names: {names}")

for face in faces:
    if face.get("span_count", 0) <= 0:
        raise SystemExit(f"Face has no generated spans: {face.get('face_name')}")
    if not 0 <= face.get("color_id", -1) <= 15:
        raise SystemExit(f"Face color id is not C64 color-like: {face}")
    for span in face.get("spans", []):
        if not 0 <= span["y"] <= 199:
            raise SystemExit(f"Span y out of C64 bitmap bounds: {span}")
        if not 0 <= span["x_start"] <= span["x_end"] <= 255:
            raise SystemExit(f"Span x range out of byte/C64 bounds: {span}")

asm = asm_path.read_text(encoding="utf-8")
for required in [
    "GENERATED BY WORKBENCH",
    "single_cube_span_face_count:",
    "single_cube_span_total_count:",
    "single_cube_spans:",
    "single_cube_spans_end:",
]:
    if required not in asm:
        raise SystemExit(f"Generated span ASM missing marker: {required}")

print("OK: generated single cube polygon spans verified.")
