#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
p = ROOT / "dist" / "moving_cube_same_depth_byte_spans.json"
asm = ROOT / "src" / "generated_moving_cube_byte_spans.s"

if not p.exists():
    raise SystemExit("Missing dist/moving_cube_same_depth_byte_spans.json")
if not asm.exists():
    raise SystemExit("Missing src/generated_moving_cube_byte_spans.s")

data = json.loads(p.read_text())
frames = data.get("frames", [])
if len(frames) < 4:
    raise SystemExit("Expected at least 4 byte-span frames")

for frame in frames:
    if frame["byte_record_count"] <= 0:
        raise SystemExit(f"Frame has no byte records: {frame['frame_index']}")
    for r in frame["records"]:
        if not 0 <= r["bitmap_offset"] < 8000:
            raise SystemExit(f"Bad bitmap offset: {r}")
        if not 0 <= r["mask"] <= 255:
            raise SystemExit(f"Bad mask: {r}")

estimate = data["optimized_c64_realtime_estimate"]
if estimate["max_estimated_frame_cycles"] <= 0:
    raise SystemExit("Invalid optimized cycle estimate")

text = asm.read_text()
for marker in ["GENERATED BY WORKBENCH", "moving_cube_byte_frame_count:", "moving_cube_byte_span_records:", "moving_cube_byte_span_total_count:"]:
    if marker not in text:
        raise SystemExit(f"ASM missing {marker}")

print("OK: moving cube byte/mask span payload verified.")
