; GENERATED BY WORKBENCH
; Source: dist/single_cube_polygon_faces.json
; Generator: tools/generate_single_cube_polygon_spans.py
; Purpose: C64-facing horizontal span fill data for one shaded cube.
; Do not edit by hand.

single_cube_span_face_count:
    .byte 5

single_cube_span_total_count:
    .word 62

single_cube_spans:
    ; face_index, color_id, y, x_start, x_end
    ; north_wall shade=red_dark spans=1
    .byte 0, 5, 86, 146, 174
    ; east_wall shade=red_mid spans=20
    .byte 1, 3, 86, 174, 174
    .byte 1, 3, 87, 172, 174
    .byte 1, 3, 88, 172, 174
    .byte 1, 3, 89, 172, 174
    .byte 1, 3, 90, 172, 174
    .byte 1, 3, 91, 172, 174
    .byte 1, 3, 92, 172, 174
    .byte 1, 3, 93, 172, 174
    .byte 1, 3, 94, 172, 174
    .byte 1, 3, 95, 172, 174
    .byte 1, 3, 96, 172, 174
    .byte 1, 3, 97, 172, 174
    .byte 1, 3, 98, 172, 174
    .byte 1, 3, 99, 172, 174
    .byte 1, 3, 100, 172, 174
    .byte 1, 3, 101, 172, 174
    .byte 1, 3, 102, 172, 174
    .byte 1, 3, 103, 172, 174
    .byte 1, 3, 104, 172, 174
    .byte 1, 3, 105, 172, 174
    ; south_wall shade=red_deep spans=1
    .byte 2, 6, 105, 148, 172
    ; west_wall shade=red_mid_dark spans=20
    .byte 3, 4, 86, 146, 146
    .byte 3, 4, 87, 146, 148
    .byte 3, 4, 88, 146, 148
    .byte 3, 4, 89, 146, 148
    .byte 3, 4, 90, 146, 148
    .byte 3, 4, 91, 146, 148
    .byte 3, 4, 92, 146, 148
    .byte 3, 4, 93, 146, 148
    .byte 3, 4, 94, 146, 148
    .byte 3, 4, 95, 146, 148
    .byte 3, 4, 96, 146, 148
    .byte 3, 4, 97, 146, 148
    .byte 3, 4, 98, 146, 148
    .byte 3, 4, 99, 146, 148
    .byte 3, 4, 100, 146, 148
    .byte 3, 4, 101, 146, 148
    .byte 3, 4, 102, 146, 148
    .byte 3, 4, 103, 146, 148
    .byte 3, 4, 104, 146, 148
    .byte 3, 4, 105, 146, 148
    ; top_face shade=red_light spans=20
    .byte 4, 2, 86, 146, 174
    .byte 4, 2, 87, 146, 174
    .byte 4, 2, 88, 146, 174
    .byte 4, 2, 89, 146, 174
    .byte 4, 2, 90, 146, 174
    .byte 4, 2, 91, 146, 174
    .byte 4, 2, 92, 146, 174
    .byte 4, 2, 93, 146, 174
    .byte 4, 2, 94, 146, 174
    .byte 4, 2, 95, 146, 174
    .byte 4, 2, 96, 146, 174
    .byte 4, 2, 97, 146, 174
    .byte 4, 2, 98, 146, 174
    .byte 4, 2, 99, 146, 174
    .byte 4, 2, 100, 146, 174
    .byte 4, 2, 101, 146, 174
    .byte 4, 2, 102, 146, 174
    .byte 4, 2, 103, 146, 174
    .byte 4, 2, 104, 146, 174
    .byte 4, 2, 105, 146, 174

single_cube_spans_end:
