; GENERATED BY WORKBENCH
; Source: goal/renderer_intent.json
; Generator: tools/generate_blockout_renderer.py
; Do not edit by hand.

draw_pit_wireframe:
    ; Milestone 3: iterate pit_line_segments and call draw_projected_edge.
    rts

draw_projected_cube:
    ; Milestone 4: draw one projected cube from projection_table.
    rts

draw_active_piece:
    ; Milestone 5: draw active piece cubes.
    rts

draw_projected_edge:
    ; Milestone 3: draw one projected edge.
    rts
