; GENERATED BY WORKBENCH
; Source: goal/renderer_intent.json
; Generator: tools/generate_blockout_renderer.py
; Projection: top_down_perspective_rings
; Do not edit by hand.

draw_pit_wireframe:
    ; Contract:
    ;   Iterate pit_line_segments and call draw_line or draw_projected_edge.
    rts


draw_projected_cube:
    ; Contract:
    ;   Input A = cube cell index.
    ;   Uses projection_table.
    rts


draw_active_piece:
    ; Contract:
    ;   Uses active_piece_start and active_piece_cubes.
    ;   Calls draw_projected_cube for each cube.
    rts


draw_projected_edge:
    ; Contract:
    ;   Draw one generated edge.
    rts
