; GENERATED BY WORKBENCH
; Source: goal/renderer_intent.json
; Generator: tools/generate_blockout_renderer.py
; Projection: top_down_perspective_rings
; Do not edit by hand.


perspective_ring_count:
    .byte 5

perspective_rings:
    ; z, width, height
    .byte 0, 176, 132
    .byte 3, 136, 100
    .byte 6, 104, 76
    .byte 9, 78, 56
    .byte 12, 58, 40
